{{- if .Values.createNamespace}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
{{- end}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: counter-image
  name: counter-image
  namespace: {{.Values.namespace}}
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: counter-image
  template:
    metadata:
      labels:
        app: counter-image
    spec:
      containers:
      - image: {{.Values.image}}
        imagePullPolicy: IfNotPresent
        name: counter-image
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 1024Mi
            cpu: 100m
          requests:
            memory: 1024Mi
            cpu: 100m
